# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
services:
  - type: web
    name: desafio-votacao-web
    runtime: docker
    plan: free
    region: virginia
    rootDir: desafio-votacao-web
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "10000"
      - key: API_SCHEME
        value: https
      - key: API_HOST
        fromService:
          type: web
          name: desafio-votacao-service
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: API_PORT
        value: "443"
